version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:Z
    working_dir: /var/www/html
    networks:
      - symfony
    restart: "no"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:Z
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:Z
    networks:
      - symfony
    restart: "no"

  db:
    image: mysql:8
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jardins
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    networks:
      - symfony
    volumes:
      - ./docker/mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - symfony
    restart: "no"

networks:
  symfony:
